# Jupyter Notebook 단축키
* `shift + enter` : 실행 후 다음에 셀 하나 추가
* `control + enter` : 실행 후 그대로 있음
* `Tab` : 자동완성 기능 / 기능 탐색 기능
* `Shift + Tab` : 해당 기능, 함수에 대한 설명서 (help 기능)

# 기타 참고
* Jupyter Notebook / Colab / 파이참 IDE 비교
https://blog.naver.com/0910243/222668318602
* 변수.~~~ 에서, 괄호가 붙는 경우와 붙지 않는 경우
(1) 괄호가 붙는 경우 : 함수
(2) 괄호가 붙지 않는 경우 : 속성
* 메서드 체이닝 method chaining : 마침표(.)로 연결 연결 해서 속성이나 함수를 끌어 쓰는 방법
* 함수에 대한 설명 기재 방법 : 아래 참고 (독스트링)
* numpy doc : https://numpy.org/devdocs/user/absolute_beginners.html#broadcasting

In [157]:
def func1(a) :
    '''
    함수에 대한 설명은 이러이러 합니다.
    '''
    return a * 2

In [ ]:
func1

# 숙제
*  sort.axis 이해
* zip 함수 이해
* 코테 방법 공유
* firebase : https://console.firebase.google.com/
* 프로그레시브 웹 앱 : https://blog.naver.com/varkiry05/222785838173
* 농수산물 분야에서의 AI 적용 분야 : https://www.irsglobal.com/bbs/rwdboard/14816
* 깃허브 블로그 만들기 : https://ahnslab.com/21-how-to-start-github-blog/
* 디스콰이엇 가입 : https://disquiet.io/

# 파이썬 기본 속성과 함수

## 파이썬 설명
* 파이썬은 인터프리터 언어 -> 줄 단위 실행이 가능
* 이에 반해, 자바는 통으로 컴파일 후 클래스파일을 실행하는 방법

## Numpy 속성
* `변수.dtype` : 변수의 데이터 타입을 반환. 행렬이라면, 행렬 안 원소의 데이터 타입을 반환
* `변수.ndim` : 변수의 차원 수를 반환
* `변수.shape` : 각 축이 몇 개인지 반환. 2x2행렬이면 (2, 2) / 3차원 2x2x3 행렬이면 (2, 2, 3)
* `배열.size` : 배열의 사이즈(len)를 반환

## Numpy 함수
* `np.arange(시작값, 종료값, 공차)` : 해당 범위만큼의 행렬을 생성. 파이썬의 range 와 비슷 
* `np.array(넣을 원소)` : 행렬의 원소값을 직접 넣어서 행렬 생성
* `np.zeros(shape, dtype=float)` : 원소 값이 0인 shape(n,m) 행렬을 만드는 것 (디폴트 자료값 = float / 지정 가능)
* `np.ones(shape, dtype=float)` : 원소 값이 1인 shape(n,m) 행렬을 만드는 것 (디폴트 자료값 = float / 지정 가능)
* `np.empty(shape, dtype=float)` : 원소 값이 'Trash Value'인 shape(n,m) 행렬을 만드는 것 (디폴트 자료값 = float / 지정 가능) - 메모리상의 쓰레기값을 원소값으로 사용하기 때문에 zeros, ones보다 속도가 조금 더 빠름. 그리 큰 차이는 아님.
* `np.linspace(start값, stop값, 몇 개를 뽑을지, endpoint = 마지막 값을 포함할 것인지 d=true)` : 특정 구간을 균등 분할한 수를 추출한다. 
* `np.sort(배열, axis=정렬기준 행)` : 배열을 정렬한다.
* `np.argsort(배열, axis=정렬기준 행)` : 배열을 정렬했을 때의 index 값을 return 한다. 즉, 정렬했을 때 작은 값이 되는 순서대로의 index 를 return.
* `np.argmax(배열)` : 배열에서 가장 큰 값의 index 값을 return 한다.
* `배열.reshape(바꿀 배열 shape)` : 배열을 특정 shape 으로 바꿈
* `np.conctenate(배열들 .. )` : 다수의 배열을 합친다(연산이 아닌 합침)  , axis = 디폴트 0. 0 = x축으로 합침 / 1 = y축으로 합침 / 2 = 3차원시 z축으로 합침
* `np.vstack((붙일 배열들))` : 수직으로 배열들을 붙임
* `np.hstack((붙일 배열들))` : 수평으로 배열들을 붙임
* `np.vsplit((나눌 배열))` : 수직으로 배열을 분리시킴 (등분)
* `np.hsplit((나눌 매열))` : 수평으로 배열을 분리시킴 (등분)
* `np.unique(배열)` : 해당 배열의 유니크 값을 반환
* `배열.transpose()` : 배열의 행과 열을 바꾸는 함수. 예로 2x3 행렬이었다면, 3x2 행렬로 바꾼다.
* `np.flip(배열)` : 배열 내 원소의 순서를 뒤집어줌. 정렬의 개념이 아님. 뒤집는 것 뿐. axis 에 따라 axis = 0이면 0축을 뒤집기, axis = 1이면 1축을 뒤집기
* `배열.flatten()` : 배열을 1차원으로 바꿔줌. 깊은 복사 (.copy 후 변경 진행)
* `배열.ravel()` : 배열을 1차원으로 바꿔줌. 깊은 복사 (원본에까지 변경이 적용됨)



## Numpy 설명
* Numpy 튜토리얼 : https://numpy.org/devdocs/user/absolute_beginners.html
* 행렬[행,열] 의 구조를 가지고 있다. (2차원 행렬시)
* 행렬은 동일한 데이터타입의 원소만을 가짐

## Numpy의 자료형
* int8, int16, int32, int64의 차이점 : 담을 수 있는 데이터의 크기이다. int8 = 8비트 int / int64 = 64비트 int = 8바이트 int 


## Numpy 배열 구조에 대한 설명
|지칭|설명|
|---|---|
|스칼라|하나의 열만 있는 배열 (1차원)|
|어레이|2차원 배열 = 행렬 / (행,열) 구조|
|매트릭스|3차원 배열|
|텐서|4차원 이상의 배열|

In [28]:
import pandas as pd
import numpy as np
np.__version__

'1.21.5'

In [41]:
# 범위 생성 arange
a = np.arange(6)
print(a)
a = np.arange('a', 'z', str)
print(a)

# n차원 배열 생성
a2 = a[np.newaxis,:]
print(a2)
a2.shape

[0 1 2 3 4 5]


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [155]:
# 범위 생성 + reshape
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
print("============================")
a = np.array([1, 2, 3, 4, 5, 6])
print(a.dtype)
print("============================")
a = np.array([1., 2, 3, 4, 5, 6])
print(a.dtype)
print("============================")
a = np.array(['1', 2, 3, 4, 5, 6])
print(a.dtype)


print(a.ndim)
print(a.shape)

int32
float64
<U11
1
(6,)


In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
print(a[0,3])
print(a[:,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
[1 2 3 4]
4
[ 4  8 12]


In [29]:
a2 = np.array([[1, 2], [3, 4], [5, 6]]) # 2차원 배열
a3 = np.array([[[1, 2], [3, 4], [5, 6]],[[1, 2], [3, 4], [5, 6]]])

print(a2)
print(a3)

[[1 2]
 [3 4]
 [5 6]]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


In [32]:
print(a2.dtype)
a2

int32


array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
print(a3.dtype)
a3

int32


array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [42]:
# np.zeros
z1 = np.zeros((5, 5), dtype=float)
z2 = np.zeros((4, 4), dtype=int)
z3 = np.zeros((3, 3))

z1, z2, z3

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [38]:
# np.ones
o1 = np.ones((5, 5), dtype=float)
o2 = np.ones((4, 4), dtype=int)

o1, o2

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

In [39]:
# np.empty

n1 = np.empty((2, 2), dtype=float)
n2 = np.empty((3, 3), dtype=str)

n1, n2

(array([[2.12199579e-314, 4.67296746e-307],
        [2.09483834e-321, 8.21212371e-312]]),
 array([['', '', ''],
        ['', '', ''],
        ['', '', '']], dtype='<U1'))

In [62]:
# sort

a = np.array([[1, 3], [4, 1]])
print("sort 전 : ")
print(a)

np.sort(a)
print("sort 후 : ")
print(a)

a = np.array([[1, 3], [4, 1]])
print("sort - axis=0 : ")
print(np.sort(a, axis=0))

a = np.array([[1, 3], [4, 1]])
print("sort - axis=1 : ")
print(np.sort(a, axis=1))

a = np.array([[1, 3], [4, 1]])
print("sort - axis=-1 : ")
print(np.sort(a, axis=-1))

sort 전 : 
[[1 3]
 [4 1]]
sort 후 : 
[[1 3]
 [4 1]]
sort - axis=0 : 
[[1 1]
 [4 3]]
sort - axis=1 : 
[[1 3]
 [1 4]]
sort - axis=-1 : 
[[1 3]
 [1 4]]


In [59]:
# argsort
# 각 값을 정렬했을 때의 index 값을 return 한다.

print("====== argsort ======")
a = np.array([3, 1, 2])
print(np.argsort(a))

# argsort 2차원배열 axis 사용

print("====== argsort axis ======")

a = np.array([[1, 3], [4, 1]])
print("== axis=0 ==")
print(np.argsort(a, axis=0))
print("== axis=-1 ==")
print(np.argsort(a, axis=-1))
print("== axis=1 ==")
print(np.argsort(a, axis=1))

====== argsort ======
[1 2 0]
====== argsort axis ======
== axis=0 ==
[[0 1]
 [1 0]]
== axis=-1 ==
[[0 1]
 [1 0]]
== axis=1 ==
[[0 1]
 [1 0]]


In [53]:
np.argmax(a)

0

## Sort axis

* 예를 들어 [[3, 0], [4,2]] 행렬
* 이의 shape = (2, 2)

* axis = 0 : (2, :) = 첫 번째 축으로 정렬 (x축) 행 내 정렬 (내 기준으로는 열 내 정렬 = 행 간 정렬)
* axis = 1 : (:, 2) = 두 번째 축으로 정렬 (y축) 열 내 정렬 (내 기준으로는 행 내 정렬 = 행 간 정렬)
* axis = 2 : (:, 2) = 세 번째 축으로 정렬 (z축) 3차원시
...
* axis = -1 : (:, 2) = 마지막 축으로 정렬 (내 기준으로는 행 내 정렬 = 열 간 정렬))


* axis = 축

In [71]:
print("== 원본 ==")
a = np.array([[3, 0], [2, 4]])
print(a)
print("== axis=-1 ==")
print(np.sort(a, axis=-1))
print("== axis=1 ==")
print(np.sort(a, axis=1))
print("== axis=0 ==")
print(np.sort(a, axis=0))

== 원본 ==
[[3 0]
 [2 4]]
== axis=-1 ==
[[0 3]
 [2 4]]
== axis=1 ==
[[0 3]
 [2 4]]
== axis=0 ==
[[2 0]
 [3 4]]


## Concatenate, Stack


In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b), axis = 0)
# np.concatenate((a, b), axis = 1) # 이건 오류, a와 b는 1차원 행렬 (1,) 형식이기 때문

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
# 2차원 concatenate
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

np.concatenate((a, b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [81]:
# 3차원 concatenate
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([[[8, 7], [6, 5]], [[4, 3], [2, 1]]])

print("====a====")
print(a)
print("====b====")
print(b)

print("====concatenate (z축) ====")
print(np.concatenate((a, b), axis = 2))

print("====concatenate (y축) ====")
print(np.concatenate((a, b), axis = 1))

print("====concatenate (x축) ====")
print(np.concatenate((a, b), axis = 0))

====a====
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
====b====
[[[8 7]
  [6 5]]

 [[4 3]
  [2 1]]]
====concatenate (z축) ====
[[[1 2 8 7]
  [3 4 6 5]]

 [[5 6 4 3]
  [7 8 2 1]]]
====concatenate (y축) ====
[[[1 2]
  [3 4]
  [8 7]
  [6 5]]

 [[5 6]
  [7 8]
  [4 3]
  [2 1]]]
====concatenate (x축) ====
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[8 7]
  [6 5]]

 [[4 3]
  [2 1]]]


In [117]:
# Stack : 특정 방향으로 배열을 붙임

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

c = np.vstack((a, b))
d = np.hstack((a, b))

print("vstack : "), print(c)
print("hstack : "), print(d)

vstack : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack : 
[[1 2 5 6]
 [3 4 7 8]]


(None, None)

## Split

In [119]:
# split 나눌 때 사용

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

c = np.vstack((a, b))
d = np.hstack((a, b))

print("vstack : "), print(c)
print("hstack : "), print(d)

e = np.vsplit(c, 0)
f = np.hsplit(d, 0)

print("vsplit : "), print(e)
print("hsplit : "), print(f)

vstack : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack : 
[[1 2 5 6]
 [3 4 7 8]]


ZeroDivisionError: integer division or modulo by zero

## Size, Shape

In [82]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c = np.array([[[8, 7], [6, 5]], [[4, 3], [2, 1]]])

print(a.shape)
print(a.size)

print(b.shape)
print(b.size)

print(np.concatenate((a,c), axis=0).size)
print(np.concatenate((a,c), axis=0).shape)
print(np.concatenate((a,c), axis=1).size)
print(np.concatenate((a,c), axis=1).shape)

(2, 2, 2)
8
(2, 4)
8
16
(4, 2, 2)
16
(2, 4, 2)


## Reshape

* 모양을 바꾸는 함수로, 인공지능 학습 과정에서 많이 쓰인다.
* 예를 들어, 3차원인 자료형을 2차원으로 바꾼 후 학습기에 넣는다거나.. 하는 필요성 때문

In [87]:
# 2차원 배열의 reshape
a = np.array([[1, 2, 3, 4, 9, 10], [5, 6, 7, 8, 11, 12]])
print(a.reshape(2, 6))
print(a.reshape(6, 2))
# 2차원 배열을 3차원으로
print(a.reshape(2, 2, 3))
# 2차원 배열을 1차원으로
print(a.reshape(12))


# 다른 방식으로 표현 (정석 방식)
np.reshape(a, (6, 2))

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [ 7  8]
 [11 12]]
[[[ 1  2  3]
  [ 4  9 10]]

 [[ 5  6  7]
  [ 8 11 12]]]
[ 1  2  3  4  9 10  5  6  7  8 11 12]


array([[ 1,  2],
       [ 3,  4],
       [ 9, 10],
       [ 5,  6],
       [ 7,  8],
       [11, 12]])

## new axis
* 새로운 축을 추가하는 것

In [94]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a의 shape : "), print(a.shape), print("\n")

a2 = a[:,np.newaxis]
print("a2의 shape : "), print(a2.shape), print("\n")

a의 shape : 
(3,)


a2의 shape : 
(3, 1)




(None, None, None)

## expand_dims
* 차원을 늘리는 것
* `np.expand_dims(원본 배열, 추가할 축 번호)` : 축 번호가 0이면 가장 앞 축으로 추가, 축 번호가 1이면 두 번째 축으로 추가

In [107]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a의 shape 원본 : "), print(a.shape), print("\n")
print("b의 shape 원본 : "), print(b.shape), print("\n")

c1 = np.expand_dims(a, axis=0)
print("a의 shape 0축 추가: "), print(c1.shape), print("\n")

c2 = np.expand_dims(c1, axis=1)
print("a에 shape 0축 추가 + 1축 추가 : "), print(c2.shape), print("\n")


d = np.array([a, b])
e = np.expand_dims(d, axis=0)
f = np.expand_dims(d, axis=1)
g = np.expand_dims(d, axis=2)
print("a, b 배열 생성 shape : "), print(d.shape), print("\n")
print("a, b 배열 + 0축 추가 shape : "), print(e.shape), print("\n")
print("a, b 배열 + 1축 추가 shape : "), print(f.shape), print("\n")
print("a, b 배열 + 2축 추가 shape : "), print(g.shape), print("\n")


a의 shape 원본 : 
(3,)


b의 shape 원본 : 
(3,)


a의 shape 0축 추가: 
(1, 3)


a에 shape 0축 추가 + 1축 추가 : 
(1, 1, 3)


a, b 배열 생성 shape : 
(2, 3)


a, b 배열 + 0축 추가 shape : 
(1, 2, 3)


a, b 배열 + 1축 추가 shape : 
(2, 1, 3)


a, b 배열 + 2축 추가 shape : 
(2, 3, 1)




(None, None, None)

## Unique 값

In [153]:
a = np.array([16, 17, 18, 11, 11, 12, 13, 14, 15, 16, 16])
print("a의 유니크값"), print(np.unique(a)), print('\n')

print("a의 유니크값 + return index=True"), print(np.unique(a, return_index=True)), print('\n')

print("a의 유니크값 + return inverse=True"), print(np.unique(a, return_inverse=True)), print('\n')

print("a의 유니크값 + return index + return inverse=True"), print(np.unique(a, return_index=True, return_inverse=True)), print('\n')

print("a의 유니크값 + return counts=True"), print(np.unique(a, return_counts=True)), print('\n')

a의 유니크값
[11 12 13 14 15 16 17 18]


a의 유니크값 + return index=True
(array([11, 12, 13, 14, 15, 16, 17, 18]), array([3, 5, 6, 7, 8, 0, 1, 2], dtype=int64))


a의 유니크값 + return inverse=True
(array([11, 12, 13, 14, 15, 16, 17, 18]), array([5, 6, 7, 0, 0, 1, 2, 3, 4, 5, 5], dtype=int64))


a의 유니크값 + return index + return inverse=True
(array([11, 12, 13, 14, 15, 16, 17, 18]), array([3, 5, 6, 7, 8, 0, 1, 2], dtype=int64), array([5, 6, 7, 0, 0, 1, 2, 3, 4, 5, 5], dtype=int64))


a의 유니크값 + return counts=True
(array([11, 12, 13, 14, 15, 16, 17, 18]), array([2, 1, 1, 1, 1, 3, 1, 1], dtype=int64))




(None, None, None)

# 슬라이싱

## 슬라이싱과 주소 참조
* 슬라이싱은 원 배열의 '주소값'을 참조한다.
* 그러므로 슬라이싱한 후의 배열의 원소의 값을 변경해주면
* 원 배열의 원소값도 변경된다.

## .copy : 주소참조가 아닌 배열 자체를 복사
* 주소 참조가 아닌, 동일한 값을 가진 배열을 복사하고 싶다면
* `배열 = 원배열.copy` 함수를 이용한다. 

In [116]:
# 슬라이싱은 원 배열의 '주소값'을 참조한다.
# 그러므로 슬라이싱한 후의 배열의 원소의 값을 변경해주면
# 원 배열의 원소값도 변경된다.

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]

print("a 배열 : "), print(a)
print("a에서 슬라이싱한 arr1 : "), print(arr1)

arr1[0] = 14
print("a 배열 + arr1의 0번 원소 값 변경시 : "), print(a)
print("arr1의 0번 원소 값 변경 후 arr1 : "), print(arr1)


a 배열 : 
[ 1  2  3  4  5  6  7  8  9 10]
a에서 슬라이싱한 arr1 : 
[4 5 6 7 8]
a 배열 + arr1의 0번 원소 값 변경시 : 
[ 1  2  3 14  5  6  7  8  9 10]
arr1의 0번 원소 값 변경 후 arr1 : 
[14  5  6  7  8]


(None, None)

# Numpy 의 연산과 비교연산, 통계

## Numpy의 비교연산
* `>, <, <=, >=` : 원소값 중 조건에 맞는 원소값을 반환한다.
* `==, !=` : 원소값이 특정 값과 같거나 같지 않은 원소값을 반환한다.
* `|` : or 의 뜻
* `&` : and 의 뜻

## Numpy의 연산
* `+, -, *, /` : 기본적인 사칙연산 가능
* `%, //` : 나누기 관련 몫, 나머지도 구할 수 있다.
* `배열.sum()` : 배열 내의 원소 값을 모두 더한 값을 반환

## Broad Case : 크기가 다른 배열 간 연산
* 크기가 다른 배열 간 연산은 행렬의 연산과 그 방식이 같다.
* 즉, 마지막 축의 값이 같거나, 어느 한 쪽이 1이면 연산이 가능하다.


## Numpy 연산과 관련된 함수
* `np.nonzero(조건)` : 조건에 맞는 데이터가 위치한 축값을 반환한다.
* `zip`

## Numpy 통계 함수
* `min, max, sum` : 최소값, 최대값, 합계를 구할 수 있다.
* `배열.max()` : 최대값
* `배열.min()` : 최소값

## 난수 함수
* `np.random` : 난수값을 생성
* `np.rangom.default_rngo(시드값)` : 난수값을 생성 (난수 생성 표에 따름 - 시드값에 따라 연산 결과는 다르나, 시드값이 같다면 동일한 난수값이 반환됨)


In [108]:
a = np.array([[1, 2], [3, 4]])

up2 = a[a>2]
print(up2)

[3 4]


In [112]:
a = np.nonzero(a<5)
a

TypeError: '<' not supported between instances of 'tuple' and 'int'

## 예시

### 연산

In [130]:
a = np.array([1, 2])
b = np.array([1, 1])

print("a, b 값"), print(a), print(b), print('\n')


plus_v = a + b
print("a + b"), print(plus_v), print('\n')

sum_a = a.sum()
sum_b = b.sum()
print("sum_a"), print(sum_a), print("sum_b"), print(sum_b), print('\n')

c = np.array([a, b])
print("c = a, b 배열"), print(c), print('\n')


d = c.sum(0)
e = c.sum(1)
print("c의 축간 sum") , print("c의 0축 sum)") , print(d), print("c의 1축 sum)") , print(e)


a, b 값
[1 2]
[1 1]


a + b
[2 3]


sum_a
3
sum_b
2


c = a, b 배열
[[1 2]
 [1 1]]


c의 축간 sum)
c의 0축 sum)
[2 3]
c의 1축 sum)
[3 2]


(None, None, None, None, None)

### BroadCast : 크기가 다른 배열 간 연산

In [136]:
a = np.array([1, 2])
b = np.array([[1, 2], [3, 4]])
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("a : "), print(a), print(a.shape), print("\n")
print("b : "), print(b), print(b.shape), print("\n")
print("c : "), print(c), print(c.shape), print("\n")

d = a * b
# e = a * c   축에서의 원소 개수가 달라 연산 불가

print(d)
# print(e)

a : 
[1 2]
(2,)


b : 
[[1 2]
 [3 4]]
(2, 2)


c : 
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


[[1 4]
 [3 8]]


### 난수값 생성

In [144]:
rng = np.random.default_rng(1)
print("난수값 생성"), print(rng.random(3)), print('\n')

print("난수값 생성 + integer로 제한"), print(rng.integers(0, 10, 7)), print('\n')

난수값 생성
[0.51182162 0.9504637  0.14415961]


난수값 생성 + integer로 제한
[8 9 2 3 8 4 2]




(None, None, None)

# 헤드1
## 헤드2
### 헤드3

|표 제목|표 내용|
|-----|-----|
|1.손원준|화이팅|
|2.김해민|대박|
|3.고준호|화이팅하자|

* 항목
* 항목

`코드는 이렇게 작성합니다.`