# Iris sklearn

In [3]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
import pickle

In [4]:
iris = load_iris()

X = iris.data
y = iris.target

dt_model = DecisionTreeClassifier(max_depth=3)
dt_model.fit(X, y)

DecisionTreeClassifier(max_depth=3)

In [14]:
a = X[10]
b = X[60]
c = X[120]

X[10], X[70], X[120]

(array([5.4, 3.7, 1.5, 0.2]),
 array([5.9, 3.2, 4.8, 1.8]),
 array([6.9, 3.2, 5.7, 2.3]))

In [15]:
dt_model.predict([a]), dt_model.predict([b]), dt_model.predict([c])

(array([0]), array([1]), array([2]))

# 모델 저장

## 피클 둘러보기

In [17]:
pickled_model = pickle.dumps(dt_model)
pickled_model

b'\x80\x04\x95\xf1\x06\x00\x00\x00\x00\x00\x00\x8c\x15sklearn.tree._classes\x94\x8c\x16DecisionTreeClassifier\x94\x93\x94)\x81\x94}\x94(\x8c\tcriterion\x94\x8c\x04gini\x94\x8c\x08splitter\x94\x8c\x04best\x94\x8c\tmax_depth\x94K\x03\x8c\x11min_samples_split\x94K\x02\x8c\x10min_samples_leaf\x94K\x01\x8c\x18min_weight_fraction_leaf\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0cmax_features\x94N\x8c\x0emax_leaf_nodes\x94N\x8c\x0crandom_state\x94N\x8c\x15min_impurity_decrease\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0cclass_weight\x94N\x8c\tccp_alpha\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0en_features_in_\x94K\x04\x8c\nn_outputs_\x94K\x01\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x19\x8c\x05dtype\x94\x93\x94\x8c\x02i8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x18\x00\x00\x00\x00\x00\x00\x00\x00

## 위에서 만든 DT 모델 저장

In [16]:
with open('pickled_model_iris.bin', 'wb') as f:
    pickle.dump(dt_model, f)

## 피클 모델 읽기

In [ ]:
# 커널 리스타트

In [3]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
import pickle

In [ ]:
# dt 모델을 실행시키면 : 커널 리스타트했기 때문에 이전 내용 없음

In [1]:
dt_model

NameError: name 'dt_model' is not defined

In [ ]:
# 피클 모델 불러오기

In [4]:
with open('pickled_model_iris.bin', 'rb') as f:
    dt_model_loaded = pickle.load(f)

In [5]:
dt_model_loaded.predict([[6.9, 3.2, 5.7, 2.3]])

array([2])